Getting somewhere!

diff --git a/.github/workflows/kubectl-validate-test.yaml b/.github/workflows/kubectl-validate-test.yaml
--- a/.github/workflows/kubectl-validate-test.yaml
+++ b/.github/workflows/kubectl-validate-test.yaml
@@ -9,20 +9,22 @@ permissions:
 
 jobs:
   changed_files:
-    runs-on: ubuntu-latest # windows-latest || macos-latest
+    runs-on: homelab-arc-runner-set
     name: Test changed-files
     steps:
+      - name: Ensure git is installed
+        run: |
+          if ! command -v git &> /dev/null
+          then
+            echo "git could not be found, installing..."
+            sudo apt-get update && sudo apt-get install -y git
+          fi
+
       - uses: actions/checkout@v4
 
-      # -----------------------------------------------------------------------------------------------------------
-      # Example 1
-      # -----------------------------------------------------------------------------------------------------------
       - name: Get changed files
         id: changed-files
         uses: tj-actions/changed-files@v44
-        # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
-        # with:
-        #   since_last_remote_commit: true
 
       - name: List all changed files
         env:
